# Site settings
title: Mark Macapagal - Biologist, Web Designer, Filipino Activist
email: mark@macapagal.net
description: > # this means to ignore newlines until "baseurl:"
  Mark Macapagal is a Cornell University graduate with a BA in Biology. He enjoys programming for the web and promoting Filipino youth-activism.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://markmacapagal.com" # the base hostname & protocol for your site
github_username: themarkofmac

# Build settings
markdown: kramdown
highlighter: rouge